import os,requests,io,json,time,threading as th
from flask import Flask,request
B=''
B+='T=os.getenv("TELE_TOKEN")or""\n'
B+='A=Flask(__name__)\n'
B+='S="XRP";E={};O=False;C=0;LC={}\n'
B+='def p(s):\n'
B+=' try:\n'
B+=' a="https://api.coinbase.com/v2/prices/"\n'
B+=' b=a+s+"-USD/spot"\n'
B+=' j=requests.get(b,timeout=8).json()\n'
B+=' return float(j["data"]["amount"])\n'
B+=' except:\n'
B+=' return 0\n'
B+='def q(s):\n'
B+=' try:\n'
B+=' a="https://api.exchange.coinbase.com/"\n'
B+=' b="products/"+s+"-USD/candles"\n'
B+=' c="?granularity=60"\n'
B+=' u=a+b+c\n'
B+=' j=requests.get(u,headers={"User-Agent":"M"},timeout=10).json()\n'
B+=' return sorted(j)[-60:]\n'
B+=' except:\n'
B+=' return []\n'
B+='def rsi(a):\n'
B+=' if len(a)<15:\n'
B+=' return 50\n'
B+=' g=l=0\n'
B+=' for i in range(1,15):\n'
B+=' d=a[i]-a[i-1]\n'
B+=' if d>0:\n'
B+=' g+=d\n'
B+=' else:\n'
B+=' l+=-d\n'
B+=' return 100-100/(1+g/l) if l else 88
